version: '3.5'
services:
  xo:
    image: ronivay/xen-orchestra
    deploy:
      mode: replicated
      replicas: 5
    ports:
      - "80:80"
    volumes:
      - xen_redis:/var/lib/redis
      - xen_xo-server:/var/lib/xo-server

volumes:
  xen_xo-server:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.240.249,nfsvers=3"
      device: ":/mnt/main/docker/xen/xo-server"
  xen_redis:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.240.249,nfsvers=3"
      device: ":/mnt/main/docker/xen/redis"
